export default {
    label: '',
    name: '',
    type: 'text',
    choices: [],
    child_of: '',
    allow_null: 'false',
    min: '',
    max: '',
    step: '',
    date_time_picker: 'date_time',
    multiline: 'false',
    default: '',
    checked: 'false',
    placeholder: '',
    help: '',
    placement: 'content',
    hide_if_not_selected: 'false',
    save_in_meta: 'false',
    save_in_meta_name: '',
};
